name: "Daily usageReport to MeshStack Sync"

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  stackit-metering:
    timeout-minutes: 10
    runs-on:
      - mesh-runners
    environment:
        name: STACKIT
    container:
      image: europe-west3-docker.pkg.dev/meshstack-infra/meshstack-container/cypress-ci
      credentials:
        username: _json_key
        password: "${{ secrets.IMAGE_PULL_SECRET }}"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install
        working-directory: stackit/metering

      - name: Run Sync stackIT
        env:
          STACKIT_SERVICE_ACCOUNT_TOKEN: ${{ secrets.STACKIT_SERVICE_ACCOUNT_TOKEN }}
          KRAKEN_API_KEY: ${{ secrets.KRAKEN_API_KEY }}
          MESHSTACK_API_ENDPOINT: ${{ secrets.MESHSTACK_API_ENDPOINT }}
          MESHSTACK_PLATFORM_IDENTIFIER: ${{ secrets.MESHSTACK_PLATFORM_IDENTIFIER }}
          STACKIT_CONTAINER_PARENT_ID: ${{ secrets.STACKIT_CONTAINER_PARENT_ID }}
        run: |
          set -e  # Fail on error
          node stackit/metering/index.ts

  ionos-metering:
    timeout-minutes: 10
    runs-on:
      - mesh-runners
    environment:
        name: IONOS
    container:
      image: europe-west3-docker.pkg.dev/meshstack-infra/meshstack-container/cypress-ci
      credentials:
        username: _json_key
        password: "${{ secrets.IMAGE_PULL_SECRET }}"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install
        working-directory: ionos/metering

      - name: Run Sync IONOS
        env:
          IONOS_USERNAME: ${{ secrets.IONOS_USERNAME }}
          IONOS_CONTRACT: ${{ secrets.IONOS_CONTRACT }}
          IONOS_PASSWORD: ${{ secrets.IONOS_PASSWORD }}
          KRAKEN_API_KEY: ${{ secrets.KRAKEN_API_KEY }}
          MESHSTACK_API_ENDPOINT: ${{ secrets.MESHSTACK_API_ENDPOINT }}
          MESHSTACK_PLATFORM_IDENTIFIER: ${{ secrets.MESHSTACK_PLATFORM_IDENTIFIER_IONOS }}
        run: |
          set -e  # Fail on error
          node ionos/metering/index.ts
